2197- allow for tiered sorting
imsweb/django-seeker pull request #120
Opened 2020-04-09 13:38 UTC by smithlc

2020-04-09 14:01 UTC, tomlinsj requested changes

2020-04-09 14:01 UTC, tomlinsj commented on seeker/views.py
> +        sort_dict.update({
I think I would have still return the dict not update

2020-04-09 14:01 UTC, tomlinsj commented on seeker/views.py
> +                sort_dict = self.sort_descriptor_method(s, sort_dict)
and have this update instead

2020-04-09 14:01 UTC, tomlinsj commented on seeker/views.py
> +                results = search.sort(self.sort_descriptor(sort))[offset:offset + page_size].params(request_timeout=self.search_timeout).execute()
why not have this 
```
if not (self.missing_sort is None and isinstance(sort, dict)):
     sort = self.sort_descriptor(sort)
results = search.sort(*sort)[offset:offset + page_size].params(request_timeout=self.search_timeout).execute()
```

2020-04-09 14:01 UTC, tomlinsj commented on seeker/views.py
> +            sort_fields.append('-{}'.format(c.sort) if sort.startswith('-') else c.sort)
I think this should be returning as well

2020-04-09 14:01 UTC, tomlinsj commented on seeker/views.py
> +                sort_fields = self.get_sort_field_method(column_lookup, s, sort_fields)
and appending here

2020-04-09 14:26 UTC, smithlc commented on seeker/views.py
> +                results = search.sort(self.sort_descriptor(sort))[offset:offset + page_size].params(request_timeout=self.search_timeout).execute()
I am not sure we want to manipulate the sort variable. It gets passed back into the context, and that might have cascading consequences  changing from a list or string to a dict.

2020-04-09 17:43 UTC, ruttenb commented on seeker/views.py
> +                results = search.sort(self.sort_descriptor(sort))[offset:offset + page_size].params(request_timeout=self.search_timeout).execute()
Couple of things here...

1. I agree with @smithlc, we don't want to store the return value of `sort_descriptor` in `sort`.
2. Be careful of introducing breaking changes.  I would move `self.missing_sort is None or isinstance(sort, dict)` back to `sort_descriptor`.  Removing this logic from `sort_descriptor` could lead to errors if any site manually calls that function or overrides the functionality of that function.

2020-04-15 15:29 UTC, tomlinsj approved these changes

2020-04-15 15:29 UTC, merged